export const EMOJIS = {
  feat: "✨",
  fix: "🐛",
  docs: "📚",
  style: "💄",
  refactor: "♻️",
  perf: "⚡",
  test: "🧪",
  build: "📦",
  ci: "👷",
  chore: "🔧",
  revert: "⏪",
  feat_scope: "🎉",
  rocket: "🚀",
  check: "✓",
  cross: "✗",
  spinner: "⠋",
  star: "⭐",
  arrow: "→",
  branch: "🌿",
  history: "📜",
  gear: "⚙️",
  lock: "🔒",
  fire: "🔥",
  bulb: "💡",
  sparkles: "✨",
} as const;
